version: '3.7'
services:
  flask:
      container_name: flask
      image: "flask:test"
      build:
        context: "/mnt/c/study/web/flask_project-docker/eval_page"
      ports:
       - "5000:5000"
      networks:
      - backend
  nginx:
      container_name: nginx
      image: "nginx:test"
      build:
        context: "/mnt/c/study/web/flask_project-docker/nginx"
      ports:
       - "80:80"
      networks:
       - backend
  mysql:
      image: mysql:latest 
      container_name: mysql 
      ports: 
        - "3306:3306" 
      environment: 
        MYSQL_ROOT_PASSWORD: 'qwerqwer123' 
      command: 
        - --character-set-server=utf8mb4 
        - --collation-server=utf8mb4_unicode_ci
      networks:
       - backend

networks:
  backend:
    driver: bridge