version: '3.7'

networks:
  my_network_name:
    name: my_network_name
    external: false

services:
  flask:
      container_name: flask
      build: ./eval_page
      image: "flask:test"
      ports:
       - "5000:5000"
      networks:
      - my_network_name
  nginx:
      container_name: nginx
      build: ./nginx
      image: "nginx:test"
      ports:
       - "80:80"
      networks:
       - my_network_name
  mysql:
      image: mysql:latest 
      container_name: mysql 
      ports: 
        - "3306:3306" 
      environment: 
        MYSQL_ROOT_PASSWORD: 'qwerqwer123' 
      command: 
        - --character-set-server=utf8mb4 
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - "./init/:/docker-entrypoint-initdb.d/"
      networks:
       - my_network_name
